<?php

namespace Database\Seeders;

use App\Models\Port;
use Illuminate\Database\Seeder;

class PortSeeder extends Seeder
{
    public function run(): void
    {
        $ports = [
            [
                'name' => 'Marina di Rimini',
                'city' => 'Rimini',
                'province' => 'RN',
                'region' => 'Emilia-Romagna',
                'latitude' => 44.0593700,
                'longitude' => 12.5687800,
                'address' => 'Piazzale Boscovich, 12',
                'description' => 'Porto turistico nel cuore della riviera romagnola con  620 posti barca.',
                'amenities' => ['wifi', 'electricity', 'water', 'fuel', 'toilets', 'showers'],
            ],
            [
                'name' => 'Porto di Sanremo',
                'city' => 'Sanremo',
                'province' => 'IM',
                'region' => 'Liguria',
                'latitude' => 43.8159300,
                'longitude' => 7.7726800,
                'address' => 'Porto Vecchio',
                'description' => 'Porto turistico della città dei fiori, punto di partenza per la Costa Azzurra.',
                'amenities' => ['wifi', 'electricity', 'water', 'fuel', 'toilets', 'showers', 'restaurant'],
            ],
            [
                'name' => 'Marina di Portofino',
                'city' => 'Portofino',
                'province' => 'GE',
                'region' => 'Liguria',
                'latitude' => 44.3032900,
                'longitude' => 9.2096600,
                'address' => 'Calata Marconi',
                'description' => 'Esclusivo porticciolo nel borgo più famoso della Liguria.',
                'amenities' => ['wifi', 'electricity', 'water', 'toilets', 'showers', 'restaurant', 'security'],
            ],
            [
                'name' => 'Porto Turistico di Ostia',
                'city' => 'Roma',
                'province' => 'RM',
                'region' => 'Lazio',
                'latitude' => 41.7348900,
                'longitude' => 12.2554800,
                'address' => 'Via dei Pescatori, 56',
                'description' => 'Il porto turistico della Capitale, ben collegato al centro di Roma.',
                'amenities' => ['wifi', 'electricity', 'water', 'fuel', 'toilets', 'showers', 'parking'],
            ],
            [
                'name' => 'Marina di Capri',
                'city' => 'Capri',
                'province' => 'NA',
                'region' => 'Campania',
                'latitude' => 40.5531400,
                'longitude' => 14.2430100,
                'address' => 'Marina Grande',
                'description' => 'Porto principale dell\'isola di Capri.',
                'amenities' => ['electricity', 'water', 'toilets', 'showers', 'restaurant'],
            ],
            [
                'name' => 'Porto di Tropea',
                'city' => 'Tropea',
                'province' => 'VV',
                'region' => 'Calabria',
                'latitude' => 38.6725300,
                'longitude' => 15.8959200,
                'address' => 'Porto di Tropea',
                'description' => 'Porto turistico della perla del Tirreno, affacciato sulla Costa degli Dei.',
                'amenities' => ['electricity', 'water', 'fuel', 'toilets', 'showers'],
            ],
            [
                'name' => 'Marina di Ragusa',
                'city' => 'Ragusa',
                'province' => 'RG',
                'region' => 'Sicilia',
                'latitude' => 36.7806200,
                'longitude' => 14.5455200,
                'address' => 'Lungomare Andrea Doria',
                'description' => 'Porto turistico nella costa sud-orientale della Sicilia.',
                'amenities' => ['wifi', 'electricity', 'water', 'fuel', 'toilets', 'showers', 'parking'],
            ],
            [
                'name' => 'Marina di Porto Cervo',
                'city' => 'Arzachena',
                'province' => 'SS',
                'region' => 'Sardegna',
                'latitude' => 41.1350400,
                'longitude' => 9.5366100,
                'address' => 'Porto Cervo Marina',
                'description' => 'Marina di lusso nel cuore della Costa Smeralda.',
                'amenities' => ['wifi', 'electricity', 'water', 'fuel', 'toilets', 'showers', 'restaurant', 'security', 'concierge'],
            ],
            [
                'name' => 'Porto di Vieste',
                'city' => 'Vieste',
                'province' => 'FG',
                'region' => 'Puglia',
                'latitude' => 41.8820100,
                'longitude' => 16.1764700,
                'address' => 'Porto Turistico di Vieste',
                'description' => 'Porto turistico nel Gargano, porta del Parco Nazionale.',
                'amenities' => ['electricity', 'water', 'fuel', 'toilets', 'showers'],
            ],
            [
                'name' => 'Porto di Cagliari',
                'city' => 'Cagliari',
                'province' => 'CA',
                'region' => 'Sardegna',
                'latitude' => 39.2110600,
                'longitude' => 9.1095300,
                'address' => 'Marina Piccola',
                'description' => 'Porto turistico del capoluogo sardo con vista sul Golfo degli Angeli.',
                'amenities' => ['wifi', 'electricity', 'water', 'fuel', 'toilets', 'showers', 'parking', 'restaurant'],
            ],
            [
                'name' => 'Marina di Venezia',
                'city' => 'Venezia',
                'province' => 'VE',
                'region' => 'Veneto',
                'latitude' => 45.4268200,
                'longitude' => 12.3465100,
                'address' => 'Isola di San Giorgio Maggiore',
                'description' => 'Marina nel cuore della laguna veneziana.',
                'amenities' => ['wifi', 'electricity', 'water', 'toilets', 'showers', 'security'],
            ],
            [
                'name' => 'Porto Turistico di Pescara',
                'city' => 'Pescara',
                'province' => 'PE',
                'region' => 'Abruzzo',
                'latitude' => 42.4584900,
                'longitude' => 14.2230500,
                'address' => 'Riviera Nord',
                'description' => 'Porto turistico principale dell\'Abruzzo.',
                'amenities' => ['wifi', 'electricity', 'water', 'fuel', 'toilets', 'showers', 'parking'],
            ],
            [
                'name' => 'Porto di Amalfi',
                'city' => 'Amalfi',
                'province' => 'SA',
                'region' => 'Campania',
                'latitude' => 40.6340600,
                'longitude' => 14.6026700,
                'address' => 'Largo Duchi Piccolomini',
                'description' => 'Porticciolo storico della Costiera Amalfitana.',
                'amenities' => ['electricity', 'water', 'toilets'],
            ],
            [
                'name' => 'Marina di Ravenna',
                'city' => 'Ravenna',
                'province' => 'RA',
                'region' => 'Emilia-Romagna',
                'latitude' => 44.4805200,
                'longitude' => 12.2810200,
                'address' => 'Via Molo Dalmazia',
                'description' => 'Porto turistico tra le pinete e il mare dell\'Adriatico.',
                'amenities' => ['wifi', 'electricity', 'water', 'fuel', 'toilets', 'showers', 'parking'],
            ],
            [
                'name' => 'Porto di Gallipoli',
                'city' => 'Gallipoli',
                'province' => 'LE',
                'region' => 'Puglia',
                'latitude' => 40.0544700,
                'longitude' => 17.9870600,
                'address' => 'Porto Turistico',
                'description' => 'Porto turistico della perla dello Ionio, nel cuore del Salento.',
                'amenities' => ['electricity', 'water', 'fuel', 'toilets', 'showers'],
            ],
            [
                'name' => 'Marina di Loano',
                'city' => 'Loano',
                'province' => 'SV',
                'region' => 'Liguria',
                'latitude' => 44.1263500,
                'longitude' => 8.2566400,
                'address' => 'Lungomare Nazario Sauro',
                'description' => 'Uno dei porti turistici più grandi della Liguria con oltre 1000 posti.',
                'amenities' => ['wifi', 'electricity', 'water', 'fuel', 'toilets', 'showers', 'restaurant', 'parking', 'security'],
            ],
            [
                'name' => 'Porto di Taormina',
                'city' => 'Giardini Naxos',
                'province' => 'ME',
                'region' => 'Sicilia',
                'latitude' => 37.8262100,
                'longitude' => 15.2649200,
                'address' => 'Porto di Giardini Naxos',
                'description' => 'Porto turistico ai piedi di Taormina, sulla costa ionica siciliana.',
                'amenities' => ['electricity', 'water', 'fuel', 'toilets', 'showers', 'restaurant'],
            ],
            [
                'name' => 'Marina di Policoro',
                'city' => 'Policoro',
                'province' => 'MT',
                'region' => 'Basilicata',
                'latitude' => 40.1829200,
                'longitude' => 16.6927100,
                'address' => 'Porto degli Argonauti',
                'description' => 'Resort portuale sulla costa ionica della Basilicata.',
                'amenities' => ['wifi', 'electricity', 'water', 'fuel', 'toilets', 'showers', 'restaurant', 'parking', 'pool'],
            ],
            [
                'name' => 'Porto di Trieste',
                'city' => 'Trieste',
                'province' => 'TS',
                'region' => 'Friuli-Venezia Giulia',
                'latitude' => 45.6475800,
                'longitude' => 13.7656100,
                'address' => 'Sacchetta',
                'description' => 'Porto turistico nel Golfo di Trieste, crocevia tra Italia e Balcani.',
                'amenities' => ['wifi', 'electricity', 'water', 'fuel', 'toilets', 'showers', 'parking'],
            ],
            [
                'name' => 'Marina di Olbia',
                'city' => 'Olbia',
                'province' => 'SS',
                'region' => 'Sardegna',
                'latitude' => 40.9228000,
                'longitude' => 9.5087300,
                'address' => 'Banchina Isola Bianca',
                'description' => 'Marina nel golfo di Olbia, porta della Costa Smeralda.',
                'amenities' => ['wifi', 'electricity', 'water', 'fuel', 'toilets', 'showers', 'parking', 'restaurant'],
            ],
        ];

        foreach ($ports as $port) {
            Port::create(array_merge($port, [
                'country' => 'Italia',
                'is_active' => true,
            ]));
        }
    }
}
